# Generated by Django 3.2.3 on 2021-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej modyfikacji')),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Karty',
                'ordering': ('name',),
            },
        ),
    ]
