# Generated by Django 3.2.3 on 2021-05-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena')),
                ('preparation_time', models.DurationField(verbose_name='Czas przygotowania')),
                ('is_vege', models.BooleanField(default=False, verbose_name='Wegetariańskie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej modyfikacji')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='cards.card', verbose_name='Karta')),
            ],
            options={
                'verbose_name': 'Danie',
                'verbose_name_plural': 'Dania',
                'ordering': ('name',),
            },
        ),
    ]
