# Generated by Django 3.2.3 on 2021-05-23 20:32

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to=dishes.models.dish_image_file_path),
        ),
    ]
